version: '3.2'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /sql_data/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: "./tests/sql_data/"
        target: "/sql_data/"

  memcached:
      image: memcached
      restart: always

  web:
    build: .
    command: /code/docker-start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
      - elasticsearch
    environment:
        - DJANGO_DB_ENGINE=django.db.backends.mysql
        - DJANGO_DB_NAME=django
        - DJANGO_DB_USER=root
        - DJANGO_DB_PASSWORD=example
        - DJANGO_DB_HOST=db
        - DJANGO_DB_PORT=3306
        - DJANGO_CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
        - DJANGO_CACHE_LOCATION=memcached:11211
        - DJANGO_CACHE_TIMEOUT=300
        - DJANGO_HAYSTACK_ENGINE=haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine
        - DJANGO_HAYSTACK_URL=http://elastic:changeme@elasticsearch:9200/
        - DJANGO_HAYSTACK_INDEX_NAME=django


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    container_name: elasticsearch
    environment:
      - cluster.name=ehwio-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
