DJANGO_DB_ENGINE="django.db.backends.sqlite3" 
DJANGO_DB_NAME="dbname.db" 
DJANGO_DB_USER="db username goes here" 
DJANGO_DB_PASSWORD="password goes here" 
DJANGO_DB_HOST="db_ip_or_hostname" 
DJANGO_DB_PORT="" 
DJANGO_LANG="en-us" 
DJANGO_TIMEZONE="UTC" 
DJANGO_STATIC_URL="/static/" 

export DJANGO_DB_ENGINE DJANGO_DB_NAME DJANGO_DB_USER DJANGO_DB_PASSWORD DJANGO_DB_HOST DJANGO_DB_PORT DJANGO_LANG DJANGO_TIMEZONE DJANGO_STATIC_URL
